### ISSUE TITLE
Explain what makes a ‘module’ a module

### ISSUE THREAD

**Issue by asteflova** [redhat-documentation/modular-docs#1]
What does a standalone and reusable module need to look like?

Module granularity. What level of information constitutes a module?

**Comment by bhardesty** [comment]
Is this issue still relevant? Between the mod docs training, the templates, and the mod docs reference guide, I feel like this should be pretty well defined. In addition, here's another good explanation that might help: https://docs.oasis-open.org/dita/v1.0/archspec/topics.html

I'm not trying to ignore this or shut down discussion though, so if there's a particular module aspect that is still unclear or which we should describe better in the mod docs reference guide, please do elaborate. Otherwise, I suggest that we close this issue.

**Comment by rkratky** [comment]
@bhardesty, you're probably right. This was motivated by questions like: "Can my module only contain a single sentence if I'm going to reuse it often?" or "Why is something a proc module only and another thing an assembly?"

Do you think we have that covered already?

**Comment by bhardesty** [comment]
@rkratky, I reviewed the latest version of the mod docs ref guide, and I think this issue is pretty well covered now. We don't directly address those questions by name, but I think it should be pretty clear from the ref guide what a module should contain and how it is distinct from an assembly.

**Comment by bhardesty** [comment]
Closing this issue since the Mod Docs reference guide and templates provide the necessary guidance.

**Comment by bprioux** [comment]
I know this issue is closed. However, it may be useful to add, early in the Mod Doc Reference, something saying that a module always consists of a heading and content/body text. The heading is what makes a module findable and scannable in tables of contents.

**Comment by IngridT1** [comment]
How about this as a tweak to your draft?
"A documentation module is an independent, self-contained chunk of information. Each module is information that a reader can understand and use by itself. A writer can use a module as a standalone article or as part of a larger body of work (an "Assembly"). A module does not depend on other documents, but it can refer the reader to other documents as additional resources.
Because a module is self-contained, it must have a clear title that briefly and clearly summarizes the subject of the module."

**Comment by ChristyWatkins** [comment]
Reopening to continue this discussion

**Comment by tylerkelly13** [comment]
Adding a note here regarding discussion from last night's triage call.
The definition of module will be added to a new glossary section to be added to the end of the modular docs reference guide. The glossary will define terms that are ambiguous for writers unfamiliar with modular docs.

**Comment by adahms** [comment]
@asteflova @bhardesty @rkratky @bprioux @IngridT1 - It looks like the Modular Documentation Reference Guide has since gained a definition of modules in the aforementioned appendix, but Tyler's definition and Ingrid's refinement thereof provide a bit more detail.

Any issues with raising a PR to include these details so that we can close this one out?

**Comment by adahms** [comment]
Hi everyone - opened #89 to help drive this one forward.

The addition is a combination of @IngridT1's suggested wording above with the existing definition in a way that retains the specific details from each.

Thoughts?

**Comment by adahms** [comment]
Hi all - #89 has now been merged, and no new additional points have been raised in the intervening months.

Closing.
