### ISSUE TITLE
Disucss the standard for file names in a modulear repo and update the guide with the decision

### ISSUE THREAD

**Issue by baruza** [redhat-documentation/modular-docs#12]
I believe that the overall consensus so far was that the title, ID, and the file name should be the same when file name should include also the type of the module (procedure_<title>.adoc, concept_<title>.adoc, reference_<title>,adoc).* 

There are a couple of challenges with this approach:

1) The file names can become really long (IMHO not a problem, consistency is more important)

2) Some file names that are reused and their title is different based on conditions cannot adhere to this rule. For example this file: https://gitlab.cee.redhat.com/red-hat-ceph-storage-documentation/doc-Red_Hat_Ceph_Storage_3-Container_Guide/raw/master/modules/procedure_updating-ceph-clusters-to-a-new-version.adoc

We should have an exception for these cases.

Thoughts? 

* Ceph team uses also "assembly_<title>", not sure if it is necessary, though, thoughts?

**Comment by asteflova** [comment]
@baruza I'm getting a 404 for the link :) Can you please double-check if it's the right link?

**Comment by baruza** [comment]
@asteflova 

Hmm it works for me. Could you make sure you are logged in to Gitlab and then access that file? Otherwise, please try this link: https://gitlab.cee.redhat.com/red-hat-ceph-storage-documentation/doc-Red_Hat_Ceph_Storage_3-Container_Guide/blob/master/modules/procedure_updating-ceph-clusters-to-a-new-version.adoc and preview the raw version..

**Comment by asteflova** [comment]
> I believe that the overall consensus so far was that the title, ID, and the file name should be the same when file name should include also the type of the module (procedure_<title>.adoc, concept_<title>.adoc, reference_<title>,adoc).*

Ack, this is a good approach.

> Some file names that are reused and their title is different based on conditions cannot adhere to this rule.

I use the attribute in the file name. For your example, it would be: procedure_updating-ceph-clusters-to-a-new-version-type-version.adoc. Would that work for your case?

> Ceph team uses also "assembly_<title>", not sure if it is necessary, though, thoughts?

I keep assemblies in a different directory than modules, so this would be extra overhead for my repo structure.

**Comment by baruza** [comment]
@asteflova 

Using the attribute in the file name works for me :) 

For the "assembly_" prefix. We started using that when we had all the files in a one directory. We moved them to root directory of the git repo (where the master.adoc is), but the prefix stays. I think that with this approach, the assembly prefix is redundant.

**Comment by msuchane** [comment]
Following up on today's meeting, I want to restate my suggestion to use directory structures instead of file-name prefixes, if possible. My reasons behind that:

- Directories are more scalable. In a large project, navigating files would be hard if all of them were in a single directory.
- Easier to read. A directory structure clearly demarcates the various bits of metadata, especially when using a graphical file manager.
- Easier to write. When you've created a directory representing the metadata "prefix", you don't have to type as much letters by hand to create or access the individual file. This applies mostly to command-line tools.
- Using file-name prefixes *feels* like reimplementing directories to me.

If we're using just the module type as the prefix, the following could be an example of what I mean:

    project_root/assembly/title1.adoc
    project_root/concept/title2.adoc
    project_root/procedure/title3.adoc
    project_root/reference/title4.adoc

Assemblies could also stay in the project root directory if that makes more sense or is easier to use.

It's also been suggested to use the context of the document as its prefix instead. I believe it would work well in addition to module types if structured like this:

    project_root/context/type/title.adoc

So, for example, something like:

    using-identity-management-containers/overview/reference/available-container-images.adoc

Late disclaimer#1: From the brief presentation, I don't have a clear idea yet what the "context" part can actually be in all instances.

I agree that the module ID should be identical to its file path, that is including the higher-level, "prefix" directories. If AsciiDoc IDs can contain slashes (and I'm guessing they can't), this would be rather straight-forward; otherwise, underscores or dots can be used as separators, as in the file-name prefixes mentioned in previous comments. For example:

- An ID with slashes: `"overview/reference/available-container-images.adoc"`
- An ID with underscores: `"overview_reference_available-container-images.adoc"`
- An ID with dots: `"overview.reference.available-container-images.adoc"`

Late disclaimer#2: I have only minimal experience with AsciiDoc. There may be technical reasons making some of my suggestions hard or impossible to implement.

Potential problems:

- When accessing an individual .adoc file, copying it to a different location or just opening it in a way that hides the directory context, metadata is (temporarily) lost or hard to see.
- ?

What do you think?

**Comment by bhardesty** [comment]
Based on previous experience, I would caution about using the context of a module as part of the module's filename or directory name. Modular docs means that any given module can be reused in any assembly. Specifying too much context in the filename or directory name limits the ability to reuse that module in different contexts.

Instead, as a general rule for module/assembly file and directory naming, I suggest specifying only the context that will always be the same within the module's intended scope. For example, if you had a multi-product doc repo, you could use directories to specify context (though I wouldn't want to get any more specific than product and module type):

```
/
|__ common  # for any "boilerplate" modules that can apply to multiple products
    |__ concept
    |__ procedure
    |__ reference
|__ product-one  # for assemblies/modules that are specific only to this product
    |__ assembly
    |__ concept
    |__ procedure
    |__ reference
|__ product-two
    ...

```
This type of directory structure balances the need to provide some amount of context (for better scalability than a flat directory structure), with the need to enable a reasonable amount of reuse within and across products. The filenames would then just be identical to the module's title and ID.

**Comment by lruzicka** [comment]
When I was trying to adopt the modular concept for the ODL Installation Guide, I used the directory approach, similar to what @bhardesty is suggesting. Now, I believe that this is the only acceptable directory approach to be used. Anything more and deeper structured would be a nightmare to work with, because of constant switching between the directories. 

I support Bara's approach, i.e. prefixing the file name with a keyword followed by the title of the module, such as `concept_command-line-interface.adoc`. This way, you can easily list modules according to its type with a simple `ls` command plus wild cards which is very convenient.

Also, the module names should be unique. I would disregard from naming the modules `procedure_something-interesting.adoc` and `procedure_something-interesting2.adoc`. If you needed to do something like that, then maybe you'd have a wonderful candidate to reuse.

**Comment by asteflova** [comment]
The Mod Docs Guide has been updated with a section named "Anchor Names and File Names".

https://htmlpreview.github.io/?https://github.com/redhat-documentation/modular-docs/blob/master/modular-docs-manual/modular-docs-manual.html

@baruza Is this sufficient to close this issue?

**Comment by baruza** [comment]
Yep, we  can close this one. Thanks for doing the housekeeping Aneta.

**Comment by asteflova** [comment]
Thanks, Bára, I'll just close this then.

@tradej It looks like no merging is necessary, but if you can, please look at #25 anyway to see if it can be closed too :)
