### ISSUE TITLE
Determine guidelines for reusing snippets/fragments of text between modules

### ISSUE THREAD

**Issue by bhardesty** [redhat-documentation/modular-docs#18]
Modules are the fundamental building block of modular docs. However, they're not necessarily atomic in that there are occasionally opportunities to reuse "chunks" of text across modules. It would be helpful to develop some guidelines on how to handle this use case to avoid spaghetti-fying our docs (i.e. transcluding a portion of a module directly into another module).

Some initial thoughts:

* Reusing chunks of text across modules should be done with caution. Reuse inherently increases maintenance complexity, and in some cases, the "inefficiency" of having a paragraph duplicated in two different modules might be better than dealing with the extra complexity of reusing the paragraph.

* As much as possible, there should be a standard place/location where all "fragments/snippets" of reusable text are stored. This prevents the spaghettification effect where a module reuses multiple snippets, each of which are included from different modules (in other words, it's really tough to maintain reusable chunks of text when those chunks are randomly sourced from all over the doc repo). Two possible options:
    - Use a single "fragments" .adoc file to hold all reusable chunks of text. Each "chunk" could be delimited by AsciiDoctor tags (http://asciidoctor.org/docs/user-manual/#include-partial). To include a chunk in a module, you would use the tag attribute to specify the chunk you want to include (as opposed to the entire file). The benefit of this option is fragment maintainability: all reusable chunks are stored in a single file, so authors never have to go "hunting" to track down where a reusable chunk is located. The downside is that the tagging required can easily get complex and difficult to maintain.
    - Put each chunk of reusable text in a separate .adoc file. Define a standard file-naming convention to clearly identify them (i.e. use a "fragment-" prefix). Since each chunk is a separate file, they can be included in modules using normal include statements. This option would be easier to use than the tagging option, and it avoids the issue of transcluding portions of one module directly into other modules. Scalability might be a concern though, since you could end up with lots of "fragment-" files.

**Comment by tylerkelly13** [comment]
+1 There are situations where snippets/fragments are useful, such as for frequently used commands, and the way these are to be handled needs to be addressed. (currently, I use a `snip-` prefix)

**Comment by tylerkelly13** [comment]
@rkratky @tradej Has this issue been raise with tooling at any point? There are a number of potiential use cases for this, in particular, standard admonitions (such as beta and tech-preview admonitions).

**Comment by tylerkelly13** [comment]
Thanks for the quick response @adahms. It seems that this discussion can now focus standardisation (such as a simple template and text for the mod-docs guide).

**Comment by tradej** [comment]
We have got this question/request multiple times in the trainings, and I agree we should standardise it. I like @bhardesty's suggestion to keep the snippets in a single file especially because it doesn't scale too well, thus discouraging reuse of snippets except for really necessary cases (when you've got 500+ lines of reusable snippets, you probably realise you're doing something wrong).

**Comment by tylerkelly13** [comment]
Added a "help wanted" for draft:

- Template
- Changes to guidelines

Sound good? @bhardesty @tradej @ncbaratta

**Comment by pbokoc** [comment]
As someone who has experience with maintaining documentation that's split into "fragments" like this, I'd like to propose standardizing this as "under absolutely no circumstances is anyone to even think of doing this". It's a nightmare to work with - it's absolutely unmaintainable. Trying to find anything becomes a huge ordeal, filenames (or naming those partial include tags) immediately become a huge inconsistent mess regardless of any reasonable guidelines, and any time anyone changes one of these fragments, they as well as anyone reviewing the changes have to check whether it still makes sense everywhere it's used, which they probably can't do by themselves since it's potentially included in places the writer and reviewer have no knowledge of, so a tiny edit snowballs into a massive issue that affects multiple people. 

We also don't have any tooling that would tell people that "you edited file X which is included in Y, Z and A, make sure it still makes sense in all contexts". Even if we eventually get a tool like that, it's going to take a while, and inevitable errors will accumulate until then.

An experienced writer with excellent good attention to detail might be able to not break anything using a lot of effort, but a newbie has little chance of accomplishing anything in a repo structured like that.

For a real-life demonstration of how bad of an idea this is, I suggest cloning the RHEL7 Install Guide from GitLab and checking out commit `cfcd3879050d4f8fb09de9fec1cc855c2f72e365` - that's the state I got the thing in. Poke around a little in the over 1200 xmls that are often included in multiple places and often contain 3 lines of headers and a single line of actual content. Make sure you're firmly seated because it's a ride. It's absolute hell and it took us years to get rid of that. Please don't bring it back.

**Comment by JStickler** [comment]
I've used snippets in the past, but my primary driver for implementing them was saving money on localization costs by reducing word count. And I was also using a proprietary tool that was designed to support snippet reuse.  I wouldn't even attempt to use snippets without some advanced tooling to support their use.

+1 to pbokoc's comment.  Snippet reuse is an advanced use case, and we're still at the beginner stage of implementing modularization.  And considering the vast size of our documentation set, it may not make any sense at all to use snippets, as snippets may just be too granular/small files to properly track.

**Comment by jenmalloy** [comment]
I think the useful of snippets/fragments depends greatly on the size of your docs. For AMQ Online, I find it really useful. But with larger projects/products (such as RHEL docs), you really need a CMS-type system to handle the complexity that can result.

**Comment by rkratky** [comment]
@VladimirSlavik Attributes don't handle multi-line snippets.

Ad the overall issue. I agree the use of snippets should be discouraged. One doesn't need to imagine the nightmare scenario Petr paints to realize that if/when the Module Library gets implemented and modules can be reused across the entire body of CCS docs, handling snippet inclusions would become a pain.

**Comment by tradej** [comment]
I agree with @pbokoc's sentiment very much, but on the other hand, I can imagine this being a non-trivial obstacle in the mod docs adoption in certain teams or communities because they want to use them.

For the above reason, I think we should standardise the reuse in the narrowest useful scope, which IMO is supportability statements or admonitions because that's for all intents and purposes 100% of the use cases brought to my attention.

**Comment by pbokoc** [comment]
I mean, I can see a use case for snippets like Wikis do (they call it templates), for example the box on the top of the page at https://fedoraproject.org/wiki/Documentation_Development_Beat. If you look at the source, the box is included as `{{Docs_beat_closed}}`, and has a [separate page](https://fedoraproject.org/wiki/Template:Docs_beat_closed) in the `Templates` category. That's useful for when you need the same disclaimer on multiple pages. I've seen a use for something like this before, usually when there was some kind of serious vulnerability (heartbleed, shellshock, poodle, ...) and we needed to tell people to update their systems in a bunch of places. The warning was always the same, so it would make sense to only write it once and edit it in that place if that's ever needed.

A really important thing about these templates is that they're never referenced by any of the surrounding text and they never reference any surrounding text either, they're completely self-contained if that makes sense. They can include links - in the vulnerability scenario, this would be a link to a page that explains what the vulnerability is and how to make sure you're not affected - but it doesn't "interact" with anything it's included in.

Something like that could work; say we make a separate folder with these templates and then we can reuse them everywhere. We could even store them all in one place and use those partial includes; I'm wary of that but I don't have any experience with doing that so it's just a kneejerk reaction.

**Comment by rkratky** [comment]
@tradej I don't think we should (or need to) standardise this. There are many ways that writers can screw with docs -- this is just one of them. I believe it would be nice to include a suggestion/recommendation (I vote for @pbokoc's wording), but that's that. The more we say "you must not", the harder it will be to achieve more universal adoption.

**Comment by bhardesty** [comment]
My original intent in raising this was to avoid the types of issues that others have raised. I've seen first-hand the chaos of trying to maintain a doc set with lots of snippets, and the un-maintainable monstrosities that result from them. However, I know of at least three legitimate cases for using them:

- Boilerplate, multi-line text that needs to be reused in multiple assemblies or modules within a doc set.

- Reusing modules between an upstream and downstream. For example, I have several modules that are the same in both the upstream and downstream, except for a key sentence, paragraph, step, or so on. Without snippets, in each of these instances, you would have to manually maintain two copies of the same module (and hope that when you change one you happen to remember to also change the other). Ifdef/Ifdefn directives don't work in this case, because we can't have downstream-only wording visible in the upstream *.adoc files.

- Automatically-generated text. In the AMQ docs (and perhaps others), we have some reference tables that are generated automatically by scripts and then included into the appropriate modules. It's most efficient (and safest) to generate all of these tables at one time, with each table in a separate *.adoc file than to have the script mucking around with the modules themselves.

Each of these use cases demonstrates that there are some particular challenges any writer might encounter (especially when working upstream-first) that could be very difficult to solve without using snippets. For this reason, I think some guidelines would be helpful. I imagine they would caution not to use snippets unless you have a particular issue that can't reasonably be solved any other way, and that they'd provide simple, clear recommendations on how to implement them.

**Comment by tradej** [comment]
@rkratky Since this is something we know writers or their managers want, I find value in making this mechanism predictable across repositories. If we do not specify how it should be done, every team will do it a different way, which will make it harder for new writers, but more importantly, for the tooling team.

@bhardesty I agree with point one and three, but I do not agree with point two. In RHOAR, we reuse modules upstream/downstream routinely, and we surround problematic parts with `ifdef` statements or use variables for parts that change. In no case have we had to maintain two nearly identical modules.

**Comment by finp** [comment]
I think this is out of scope of this project, but there is value in groups sharing techniques, and implementation could coincide with implementation of FCC. Could this discussion run parallel to the project, perhaps in the wiki of this repo (currently disabled).

**Comment by mishaone** [comment]
I'm normally for limiting module types to the ones already defined because opening them up means a lot of, as has been mentioned earlier, contextless snippets that are hard to reuse. However, I think there's a good case to be made for things like admonitions or standardized feature types, such as tech preview, to be reused across the department with very little change being required generally.

**Comment by finp** [comment]
@bhardesty @mishaone  our project (aerogear) uses snippets and it would be good to have a standard.  But would this  be better placed in  https://github.com/redhat-documentation/community-collaboration-guide given that some communities already have a standard?

Also, I've been looking at https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/scripts/asciidoc-coalescer.rb as a method to:
* export a module to aura
* provide a easy to edit asciidoc representation of lots of partials
If you're interested, ping me to see what I've done (not ready for prime time)

**Comment by finp** [comment]
@tylerkelly13  I don't have an estimate, and I don't think it would be a standard, more a description of common practises in the same way as there are multiple file structures and multiple build methods described in https://redhat-documentation.github.io/community-collaboration-guide/

**Comment by finp** [comment]
+1 Tyler

**Comment by ritz303** [comment]
Closing this issue, it was fixed by PR #77.
