### ISSUE TITLE
Modular Docs should mandate the structure of anchors

### ISSUE THREAD

**Issue by vikram-redhat** [redhat-documentation/modular-docs#44]
Looking at https://redhat-documentation.github.io/modular-docs/#reusing-modules, the text recommends that 

> "When you create content in modules, you can use the same module multiple times in an assembly without having to replicate information in multiple source files. However, in order to facilitate module reuse, you must embed a document attribute variable in the anchor name for the module and then define that variable in the assembly each time the reused module appears. If the variable is not embedded and assigned, an error appears at build time reporting the duplicated anchor ID."

Shouldn't then the use of the variable be made mandatory for any new content by specifying it in the AsciiDoc Markup Conventions? https://redhat-documentation.github.io/asciidoc-markup-conventions/.

If I (working in OpenShift docs) want to include a module from the OpenStack docs, and those docs don't have the variable (context) in the headers, the books will not build due to the above mentioned issue. I would then have to request the OpenStack team to modify the headers which will add layers of issues to the whole process.

If we mandate that all new attributes have the _context_ added, this will make it easier for the future success of modular docs.

**Comment by rkratky** [comment]
+1

One consideration though: wouldn't it be better then to also mandate that the `context` variable is always set in assemblies, so that when modules are included, the variable is never missing/empty?

**Comment by vikram-redhat** [comment]
@rkratky - true. So all assemblies should have a `context` variable defined and all anchors should be of the form [id='section-header_{context}'] where only the `section-header` should be defined by the individual teams/authors.

**Comment by ritz303** [comment]
@vikram-redhat : Yes, you make a good point.  In mandating this, we will keep things consistent and with consistency, it will be a little easier for others to build tooling around a modular content model.  I also feel this still gives the individual teams/writers some flexibility over a naming standard that makes sense for their product. 

It makes sense to modify the language in the [AsciiDoc Mark-up Conventions Guide](https://redhat-documentation.github.io/asciidoc-markup-conventions/), instead of saying:

The `{context}` variable is recommended ...

I would replace "recommended" to "required".

Also, we would need to update the NOTE under the first step in this [section of the Mod Docs Ref Guide](https://redhat-documentation.github.io/modular-docs/#reusing-modules), also changing "recommended" to "required".

I agree with rkratky, the assembly is where the `context` attribute should be defined.

+1

Best Regards,
Aron

**Comment by vikram-redhat** [comment]
@ritz303 thanks. 

@rkratky - what needs to happen to update the modular docs language in that case? We should also make it a part of the templates/guidelines that @ChristyWatkins is creating that is to be distributed to the various teams. I am tagging all, but if I can make it happen, please let me know.

**Comment by rkratky** [comment]
@ritz303 I'm out in Feb -- Could you please mention this in ccs-mod-docs?

**Comment by ritz303** [comment]
@rkratky : Enjoy the time off!  I'll email the team later this week, I'm in the middle of a release at the moment.

**Comment by bprioux** [comment]
Which is the requested requirement, or both?
   (1) that every newly-written module must include a {context} suffix with an underscore to the anchor name in the format [id='anchor-name_{context}']? 
   (2) that only the {context} document variable should be used to control module reuse in a module anchor & assembles that reuse that module to enable module reuse? 
    I ask because, in discussing this with a few writers, they expressed concern about (1), having to include the _{context} suffix at the end of the anchor name of every new module even if there is no known or expected reuse of the module when it is first created. Requirement (2), using only the {context} variable to control module reuse, seems to support the standardization this MR seeks but does not require it in every module.

I also wonder if some of this context work can be automated in the doc build at some point, instead of coded manually. The problem of a doc build breaking because a module is reused a few times in 1 assembly or in 1 guide seems like a bug. Could the build be modified to understand the unique context of a module and then create unique module output for each context, no matter how many times or where the module is reused?

**Comment by vikram-redhat** [comment]
@bprioux - sorry I didn't see your comment till now.

The requirement is for (1). If we don't do this, then we cannot say with any confidence if a module inclusion will be successful as the build will likely fail anytime a module is reused (defeating the purpose of a reusing modules). I don't think this is a bug.

The implementation side of things, I am not sure if the tooling can support this natively. This is a question for Carlos Munoz (I can't seem to tag him though).

--
@rkratky @ritz303 I was wondering what the status of this is though? Has it been ported into the docs?

**Comment by ritz303** [comment]
@vikram-redhat : No, we haven't updated the Mod Docs Reference Guide yet.

**Comment by vikram-redhat** [comment]
@ritz303 @rkratky - Any update on this?

**Comment by ritz303** [comment]
@vikram-redhat : Extremely sorry for the massive delay here!  We have updated the modular doc templates to reflect the current anchor tag naming standard.  I'll submit a PR to update the mod doc ref guide content[1] to better reflect this change in the templates.

[1] - https://redhat-documentation.github.io/modular-docs/#anchor-and-file-names

**Comment by tylerkelly13** [comment]
@vikram-redhat has indicated that:
> If we mandate that all new attributes have the context added, this will make it easier for the future success of modular docs.
Was not addressed by #67.
I'll add a pull request regarding the need for _context_ to be defined in assemblies.
Note that if the context variable is used in a module but is not defined in the assembly, asciidoc builds will fail.

**Comment by ChristyWatkins** [comment]
Triage call note: 
There was a hanging item that has been solved in PR 73. Closing this item.

Link to doc explaining the hanging issue: https://redhat-documentation.github.io/modular-docs/#reusing-modules
