### ISSUE TITLE
Differentiate between "required" by Red Hat internal tooling and suggested "best practice"

### ISSUE THREAD

**Issue by vikram-redhat** [redhat-documentation/modular-docs#60]
Hey all,

We should provide a section in the reference guide to indicate what parts of the reference guide are mandatory and what is left for the individual teams to decide.

One of the goals (I hope) of this and the related initiative of FCC is to standardize the processes and the way we write our docs going forward. This reference guide is a great initiative towards that goal but  it leaves it up to each team to decide which parts they want to implement, if any.

I worry that this will lead to a situation where everyone is doing their own thing; taking in parts that the teams are comfortable adapting and leaving others. While some of this is unavoidable considering we are working with multiple upstream communities, we should be able to mandate many or most of the guidelines.

We should mandate (in the context of modular docs):
* file name structures
* module location structure
* assembly location structure
* image directory location
* file directory location
* use of headings (depth and correct usage)
* use and syntax of anchor ids
* use of external links
* template structure
* use of xrefs

I am probably leaving some others, but you get the picture.

If teams don't confirm to these mandates when they are rewriting their docs, then we shouldn't consider those docs modularized. Otherwise, 2 years from now, we will have multiple doc sets, written in their own vision and interpretation of what modularization is.

This is a great time to do this as many teams are putting a lot of time and energy into ripping old documentation and starting anew. Why not set some mandatory standards in place to make this job easier and consistent across teams?

**Comment by JStickler** [comment]
+1 

Especially if the publication tooling is going to rely on any of these standards in order to generate and serve modularized docs.  The writers need to know where diverging from the recommendations will break the tooling and where there's room for interpretation.

**Comment by ncbaratta** [comment]
I agree that we need this section! I don't agree that we should mandate the following:

- file name structures
- module location structure
- assembly location structure
- image directory location
- file directory location

These are the kind of things that should be defined by each project in a configuration file.

**Comment by pmkovar** [comment]
I'd argue that the tooling should be designed around the content, not the other way round.

Before making any of these mandatory, please make sure you work with teams sharing content upstream to ensure we don't break too many things. I agree with @ncbaratta these should be configurable.

**Comment by leswilliams44** [comment]
Is a configuration file a common practice for our documentation? I was guided to follow the structure that an established team was using, and it seems many teams are follow a structure similar to that. The goal was to make it easier for teams to interact because they had a common structure.

Here is my file structure. 
https://gitlab.cee.redhat.com/dotnet4rhel-documentation/dotnet-documentation/blob/master/README.md

**Comment by vikram-redhat** [comment]
@leswilliams44 makes the exact point I am trying to make with an example. In the absence of standards, teams will start making their own. Let's avoid that. Let's mandate that we have these standards and all new project teams must follow that.

@ncbaratta and @pmkovar - I don't care about the things that we standardize. If we are going to say that teams can choose their own file names, for example, _then_ that is a standard and let's write that down. But there are things that we must standardize, and we should write those things down and enforce.

We are the at the start of something big and far reaching. Let's not start creating a standards per project team.

**Comment by pbokoc** [comment]
@vikram-redhat Even if you don't care about _what_ you standardize, you're still talking about settling on a single standard and forcing it on every one of the various upstream communities Red Hat writers work with. I don't see that going over well. Different projects have different needs and Red Hat needs to respect that.

**Comment by fbolton** [comment]
I think that Apache Maven might might serve as a model for its approach to standardizing directory layout. Maven depends _strongly_ on a standardized layout -- for example, if you drop Java source code into the `src/main/java` directory, it magically gets built whenever you run Maven: no configuration needed. Consequently, you can do an awful lot of things in Maven with zero configuration, just relying on the directory structure.

On the other hand, Maven is 100% configurable: if necessary, you can customize the location of every single directory and move it to a non-standard location. This is frowned upon, but is sometimes necessary if you inherit a non-standard legacy directory structure.

Generally, a standardized layout is an excellent idea, but we need to be able to accommodate two special cases:
1. Upstream documentation projects. For example, in the case of our upstream Apache projects, there is 0% chance of us being able to enforce a directory layout upstream.
2. Recently acquired companies, whose docs might have a non-standard layout.

**Comment by vikram-redhat** [comment]
> @vikram-redhat Even if you don't care about what you standardize, you're still talking about settling on a single standard and forcing it on every one of the various upstream communities Red Hat writers work with. I don't see that going over well. Different projects have different needs and Red Hat needs to respect that.

@pbokoc - well, can we enforce this on Red Hat content? When it enters the downstream, can we set standards there?

We are moving towards a whole new modular structure for our docs across all our products and _that is a new standard_. If we can enforce that while still working with upstream communities, I fail to see why we can't have standards for downstream content separate from the upstream.

**Comment by vikram-redhat** [comment]
@fbolton - I used to love working with Maven. Standards based, easily identifiable structure across any Maven project. And still configurable if your project required it.

I think the choice of directory structure is going to be driven by the tooling team and I think we should do so (enforce a directory structure). I understand we can't force this on upstream projects, but we could do this for acquired companies (as we are doing with CoreOS).

**Comment by rkratky** [comment]
@vikram-redhat I understand your concern, but please consider how much easier it would be not to force one directory structure on everyone. Having a configuration file would ensure flexibility on the part of writing teams, as well as provide stable mapping for the tooling team. Consider the following example:
```
module_dir: /src/docs/topics/modules/
assembly_dir: /src/docs/topics/
images_dir: /src/docs/images/
common_attributes: /src/docs/meta/
```
This is, of course, just an example. But having a set of definitions like this would satisfy both sides of this argument, I believe.

There already is a `build.cfg` file used by the tooling team that needs to be included in some repos. I'm sure its function could be extended to cover things like this.

**Comment by ncbaratta** [comment]
> We are moving towards a whole new modular structure for our docs across all our products and that is a new standard. If we can enforce that while still working with upstream communities, I fail to see why we can't have standards for downstream content separate from the upstream.

@vikram-redhat what I think you're missing is that those of us working with upstream communities are mirroring our repositories to the downstream. We don't have separate content up and downstream, we work closely with communities and compromise on things like file naming and directories in order to benefit from the shared content and collaboration.  I know that in my upstreams everyone has been happy to follow the new modular guidelines in terms of breaking up the content and using the module types - but the file naming and directory changes are a harder sell because there is no practical reason for things like that.

**Comment by vikram-redhat** [comment]
Hey all,

So the discussion has veered off into directory and file name structures, which is not the main point of _this_ issue. The main point is about standardizing our process and guidelines for this guide that all teams are using. If the consensus is that file names and directory structures should not be mandated, that is fine (but please add your thoughts to https://github.com/redhat-documentation/modular-docs/pull/61).

Can we agree on:

a) Creating a section in this guide and listing mandatory guidelines as an easy reference.
b) Putting together a list of items that are mandatory (I provided a list in my first comment).
c) Communicating that to all docs teams?

**Comment by ncbaratta** [comment]
@vikram-redhat I agree with A & C and 1/2 of B.  I don't think we should make everything in your initial list mandatory (as I said before).  So I agree with everything except:

- file name structures
- module location structure
- assembly location structure
- image directory location
- file directory location

**Comment by bhardesty** [comment]
@vikram-redhat, agreed. Adding this section to the guide would be very helpful, IMO. I'm sure we'll need to discuss the list of items for point B, but we can do that through a PR.

**Comment by pbokoc** [comment]
@ncbaratta @vikram-redhat _Any_ mandatory guideline can potentially cause a conflict with an upstream community if their existing guidelines are different and the two sets can't be reconciled - and Red Hat can't force an upstream community to change their guidelines so that Red Hat's internal tooling can work with their content. I mean, sure, we can try, but I don't think that's a good approach.

Red Hat has vastly more resources than most upstream communities, so I think it's Red Hat that should accomodate. We're professional writers, we have a group of full time professional tooling developers, a bunch of content strategists and DPMs; on the other hand a lot of upstream communities have barely a couple of volunteers who occasionally write docs in their spare time, and very little technical/infrastructure support.

**Comment by JStickler** [comment]
@pbokoc, all the more reason to clarify which of the guidelines are recommendations and which are requirements for the tooling to work correctly.  That way those of us working in upstream communities can make the _smallest_ number of changes possible as we modularize our documentation.

**Comment by mishaone** [comment]
+1 "mandatory" guidelines help us standardize what we're doing as much as possible. There's no penalty for not following them, but having them helps us all be on the same page as much as possible, which is sorely lacking at the moment.

Of course, it's not possible to force this onto upstream communities and projects working heavily in the upstream would be diverging from the guidelines as fits the project.

**Comment by pmkovar** [comment]
> There's no penalty for not following them

I think the penalty is there in that if you diverge, you might end up being unsupported by the downstream tooling? This needs to be further clarified. Also, what @JStickler said.

**Comment by mishaone** [comment]
We need clarification on that point because the impression I've gotten is that the tooling does not mandate most of these guidelines (except for his like what elements a module must include, etc.)

**Comment by vikram-redhat** [comment]
@mishaone - hey.

At the minimum, tooling mandates:

* No xrefs within modules.
* No includes within modules.
* Concept and reference modules have title, introduction statement. 
* Procedure modules have title, introduction statement, and procedure (with steps) as required elements. 

Further, and I suspect eventually, we will need to mandate the issue described in https://github.com/redhat-documentation/modular-docs/issues/44 regarding anchor ids. Although I really think we should mandate that now so everyone starts using them now otherwise module reuse across products will not work.

Finally, I think we should mandate some of these guidelines to drive consistency across how we do product documentation. Some of these things are unknown at this point in time (what will tooling require from us), but if we (CCS) are consistent, we can drive tooling to build the tools around our consistent doc sets.

**Comment by mishaone** [comment]
Agreed, Vikram. It's been a long thread so I'll copy the originally proposed mandatory guidelines below:

* file name structures
* module location structure
* assembly location structure
* image directory location
* file directory location
* use of headings (depth and correct usage)
* use and syntax of anchor ids
* use of external links
* template structure
* use of xrefs

Only some of these are mandated by the tooling (i.e. would break things). The rest, I would think, are more like recommended guidelines and can be worked around or altered on a per project basis of upstream demands it.

**Comment by adahms** [comment]
@vikram-redhat - Thank you for starting this discussion.

A number of good points and some very valid concerns have been raised in this thread already, so I wanted to leave a comment to acknowledge that the tooling team is indeed aware of these concerns, and that one of the main challenges we face in developing the software for this solution will be to find the right balance between providing sufficient structure while also keeping the needs of our diverse teams in mind.

As we move forward, I would encourage everyone to continue to keep in mind that these efforts are going to involve change of some kind on all fronts (I know you know this, but it's always good to call out), but that we are still early enough in our work to affect the kind of change that does take place, which I see as one main aims of the discussion Vikram is driving here.

In regards to the point about how the documentation process should drive the requirements of the software and not the other way around, I completely agree, and want to affirm that this is indeed the approach we are taking. The new command-line tool and module library are going to provide validation of modules to ensure that aspects of them meet set requirements, and the main driver of deciding what falls in or outside that range of acceptability will be these templates rather than developing the software first and building the templates around that.

While this will still necessarily introduce some restrictions, we are also trying to accommodate as much of the flexibility that teams working with upstream communities might require, and this has been a major topic for discussion. Consideration for upstream communities has been one of the main drivers behind the reason we are looking to apply metadata in the module library rather than directly in the source files themselves, and why we are looking at assemblies as collections of modules in the way the downstream might require without mandating that upstream communities organize their content in the same way ('mandating' such a thing being impossible to begin with) or restricting how content is organized there.

What I would like to see coming out of the discussion here is a list of basic requirements or general concerns that everyone has to make sure these are being captured and considered. We should soon have the ability to actually test some of the software and see how close it comes to the mark well ahead of the time when any restrictions might come into place across the board, but the sooner we understand the central areas of concern, the more easily we can incorporate some of these into the ongoing work.

**Comment by mishaone** [comment]
Thanks, @adahms. It's good to hear the tooling perspective on this.

To summarize (and return to the scope of the original comment), are there any objections to mandatory guidelines around the following as a minimum for consistency:

- file name structures
- module location structure
- assembly location structure
- image directory location
- file directory location
- use of headings (depth and correct usage)
- use and syntax of anchor ids
- use of external links (no Xrefs for now)

**Comment by laubai** [comment]
Other than the phrase "mandatory guidelines" being something of a contradiction, no objections here.

**Comment by mishaone** [comment]
@bhardesty not at all! I want to drive this forward (mostly because it's been open for a while and I think the basics are something we should be able to agree about and lock down for now, at least) but definitely not at the expense of someone's valid objections.

I should clarify since it seems the tongue in cheek naming for the "mandatory" guidelines did not translate well at all. AFAIK there are very few things in RH and in our department that are mandatory. The correct name would be along the lines of fundamental things we should all be doing when implementing modular docs. 

Additionally, based on my understanding, the tooling is in the early stages of development at the moment, and so there is very little that should be considered set in stone at this point, but we definitely want some things to be very strong suggestions. For example, the templates. There's absolutely nothing stopping people from drastically deviating from the templates but there are good reasons to identify the module types we want and discuss any outliers and what the case is to include support for them in the tooling (for example, "snippets" such as adminitions or Tech Review text). 

If anyone has any specific ideas about outliers from the basic guidelines, possibly something that is absolutely required upstream, for example, I'd recommend ensuring that the tooling team is aware of it so that they can include flexibility around it.

Based on this, I'd like to lock down some basic guidelines that we can all agree on, not because they're mandated by someone, but because they make sense to us and are beneficial.

**Comment by pmkovar** [comment]
> I should clarify since it seems the tongue in cheek naming for the "mandatory" guidelines did not translate well at all.

Can we just rename this issue then and rename it from saying *mandatory* to something like *recommendations*? That is, we want to document the SHOULD's, not MUST's?

There have been concerns raised about *mandating* the directory/filename structure, but the summary does not reflect that.

**Comment by mishaone** [comment]
^ Absolutely. I believe @vikram-redhat was about to  do just that earlier but may have been sidetracked.

**Comment by tylerkelly13** [comment]
I've changed the title of this issue to better reflect the intent.

Some of the suggestions in the modular docs are related to what is required by the Red Hat CCS Tooling team, while other suggestions are "best practice".

It should be clearer so that teams that share documentation directly (work in the same repo) know what is required by the tooling, so they can discuss these issues with upstream contributors.

**Comment by tylerkelly13** [comment]
sorry, there was a few typos. I was in a hurry when I wrote that.

**Comment by ChristyWatkins** [comment]
After the triage meeting yesterday and a quick chat with Vikram, I think all of these issues and PRs meet the items in this one large issue:

- File name structures addressed in the Ref Guide [here](https://redhat-documentation.github.io/modular-docs/#anchor-and-file-names)

- File directory structures including modules, assemblies, and images: [issue 49](https://github.com/redhat-documentation/modular-docs/issues/49)

- Use of headings: [PR 56](https://github.com/redhat-documentation/modular-docs/pull/56), [PR 51](https://github.com/redhat-documentation/modular-docs/pull/51), and clarifications with [issue 68](https://github.com/redhat-documentation/modular-docs/issues/68)

- Use of and syntax of anchor IDs: [PR 67](https://github.com/redhat-documentation/modular-docs/pull/67) and [issue 58](https://github.com/redhat-documentation/modular-docs/issues/58)

- Use of xrefs and external links: [issue 64](https://github.com/redhat-documentation/modular-docs/issues/64)

Because the items in this issue are reflected in the PRs and issues above, I'm closing this issue.
