### ISSUE TITLE
How to use {context} in links?

### ISSUE THREAD

**Issue by scholzj** [redhat-documentation/modular-docs#72]
Hi,

We are currently discussion following issue. We have two assemblies which are included into multiple sections and link to each other:

```
- assembly-X (context=ctx-x)
    - assembly 1  <--\
    - assembly 2  ---/
- assembly-y (context=ctx-y)
    - assembly 1  <--\
    - assembly 2  ---/
```

Since each of these sections have different context,m we currently set the link like this using the `{context}`: `xref:assembly-1-{context}`. And it works fine. 

However, if we include the module also somewhere else, like for example this, it will stop working.

```
- assembly-X (context=ctx-x)
    - assembly 1  <--\
    - assembly 2  ---/
- assembly-y (context=ctx-y)
    - assembly 1  <--\
    - assembly 2  ---/
- assembly 2 --------------> ?
```

On the other hand, if we use hard coded context instead of `{context}`, such as this: `xref:assembly-1-ctx-1`, it also doesn't work perfectly. Because it always links into one particular section and leads the user out of context.

```
- assembly-X (context=ctx-x)
    - assembly 1  <--\       <-----------\   <--\ 
    - assembly 2  ---/                   |      |
- assembly-y (context=ctx-y)             |      |
    - assembly 1                         |      |
    - assembly 2 ------------------------/      |
- assembly 2 -----------------------------------/
```

Is there any recommended approach how to deal with this?

Thanks

**Comment by tylerkelly13** [comment]
@scholzj are you setting a context in each assembly, and adding the context to the parent-context for the nested assemblies? this may be the best solution in this situation.
```
ifdef::context[:parent-context: {context}]
ifdef::parent-context[:context: {parent-context}-<assembly-context>]
```
Alternatively, use `ifeval`s and URIs as a 'hacky' solution

**Comment by tradej** [comment]
I always advise against linking because it breaks the flow of information (we want the reader to read the document from top and continuing onwards without having to click a single link, preferably), but if you absolutely need the link there, @tylerkelly13's solution is IMO the best one.

I think this mechanism needs an example in the guide, with a big warning that linking out of context is really not something we want to do at all.

**Comment by tylerkelly13** [comment]
"" a big warning that linking out of context is really not something we want to do at all.""
Is an issue that has also been raised in issue #64

**Comment by scholzj** [comment]
> I always advise against linking because it breaks the flow of information (we want the reader to read the document from top and continuing onwards without having to click a single link, preferably), but if you absolutely need the link there, @tylerkelly13's solution is IMO the best one.

If you advise against linking - what is the solution you advise to solve the fact that the software is complex and there are related parts which the user needs to be pointed to? Would just tell the user to search for the relevant information?

I guess if we once really get to have the documentation based on personas and user stories you could just include it there. But you cannot include the things again and again in the document which is structured as a book.

And TBH, I'm also not sure how does setting the context and parent context help with the links. We are already using that, it doesn't really solce the problem with the linking ... or if it does I somehow missed it :-(

**Comment by tradej** [comment]
> But you cannot include the things again and again in the document which is structured as a book.

We can, and we do (at least for the time being). We know for a fact that our readers do not read the book from top to bottom, so multiple inclusions of the same module in one book are absolutely allowed, and do not result in a markedly worse user experience. Once we do away with the book model, this will no longer be an issue due to a different linking mechanism.

----

As for how `parent-context` solves the issue: You use the `{parent-context}` attribute if it is set, and a hard-coded reference if it isn't, for example:

```
assembly-x
    :parent-context: {context}
    :context: foo
    include::assembly-1.adoc[]
    include::assembly-2.adoc[]
    :parent-context!:

assembly-y
    :parent-context: {context}
    :context: bar
    include::assembly-1.adoc[]
    include::assembly-2.adoc[]
    :parent-context!:

assembly-1
    :parent-context: {context}
    :context: {parent-context}-baz
    ...
    [id='title-name_{context}']
    ....
    :parent-context!:

assembly-2
    :parent-context: {context}
    ...
    For more information, see
    ifdef::parent-context[xref::title-name_{parent-context}-baz]
    ifndef::parent-context[xref::title-name_foo-baz]
    :parent-context!:
```

In the following arrangement, the context in the `xref` ID in `assembly-2` will render as:

* `foo-baz` in `assembly-x`,
* `bar-baz` in `assembly-y`, and 
* `foo-baz` if rendered separately.

That means that when included in an assembly (when all assemblies have `parent-context` set and unset at the end), it points to the ID within that assembly, and if not included in an assembly, it is obvious where it will point.

**Comment by scholzj** [comment]
Ok, I understand now what you mean with the `ifdef`s. Thanks for clarification. 

TBH I'm not sure I agree that sharing the same module again and again in a guide is what the users want. But I'm sure you have it backed with some studies and will respect it ;-).

I think you clarified the problem I had ... so I will close this issue. 

Thanks a lot for your help!
