### ISSUE TITLE
Recommendation for a Prerequisites list that is a single prerequisite

### ISSUE THREAD

**Issue by IngridT1** [redhat-documentation/modular-docs#80]
The question that came up when we were reviewing sample modular docs (flagship or topnotch modular docs) is:

* How should we format the Prerequisites section if there is a single prerequisite? Should the title still be "Prerequisites"? Should the list be bulleted even if it's just a single prerequisite? 

At this point, there's no explicit guidance. But the current recommendations from @ChristyWatkins, Betty Prioux, and me are:

* Yes, let's bullet the list even if it's just a single bullet (based on bulleted list recommendations from the IBM Style Guide).
* Let's always make the title "Prerequisites" even if there is just a single prerequisite. 

Betty, Christy, and I all prefer to keep the formatting consistent for ease of scanning. We would like this to be an official recommendation in the Mod Docs Reference Guide.

**Comment by ritz303** [comment]
+1, I agree on being consistent.

**Comment by mishaone** [comment]
Definitely +1 for consistency.

**Comment by vikram-redhat** [comment]
+1

**Comment by jenmalloy** [comment]
I'm all for consistency, but I'm not sure about this part: 
"Yes, let's bullet the list even if it's just a single bullet (based on bulleted list recommendations from the IBM Style Guide)."
The IBM Style Guide says this (p. 79 in my edition): "Use at least two list items in an ordered list. You can have one item in an unordered list if the intention is to match the format of other unordered lists in the same area.”
I don't think this case fits the second sentence though, since there are not other unordered lists "in the same area." Or maybe I am missing a key point? 
(Full disclosure: I was taught that lists must have at least two items. One item takes the form of a sentence.)

**Comment by sterobin** [comment]
I agree with @jenmalloy's points, and with the notion that bulleted lists by nature need at least two items, but I'm fine going with "Prerequsities" plural with single bulleted items for the sake of consistency and simplicity, especially in cases of ifdefs like @VladimirSlavik  mentions. We can go against norm and logic so long as we do so deliberately and for a greater gain, in this case, consistency and simplicity. I think that is the case here, so +1 from me.

Just to be clear, when I say imo we'd be going against norm and logic (which I again am in favor of), here's what I mean:

Note Jen's reference to the IBM SG, on bullets. There's explicit direction to avoid single items in _ordered_ lists, but only implicit direction to avoid the same in unordered lists. Chicago implies the same, but again, not explicit on unordered. Style guides aside, thinking logically, bullets in lists have a function of pointing to each line so you can quickly identify the line items in that list. Numbers do the same thing in ordered lists. But if there's only one item, it's not a list, it's just a note basically. So the general consensus I've seen is to not bullet single items, because the bullet isn't necessary, unless for consistency with surrounding lists, as IBM says. For fun, Google if one should bullet single lists or not, and notice that there's a debate but that the majority are in favor of non bulleting. If you consider yourself a descriptivist, than a majority usage says something. If pre(pro)scriptivist, then maybe that doesn't sway you. :)

But again, my favorite Dalai Lama quote: "Know the rules well, so you can break them effectively."

**Comment by ritz303** [comment]
This issue was resolved by PR #86. Closing this issue.
